name: Create management zone in Dynatrace
on:
  workflow_dispatch:
    inputs:
      applicationName:
        description: 'Name of the management zone'
        required: true
      hostGroupDescription:
        description: 'Description of the management zone'
        required: true

jobs:
  create_management_zone:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger API Call
        run: |
          curl --location 'https://fnb80541.live.dynatrace.com/api/v2/settings/objects' --header 'Accept: application/json; charset=utf-8' --header 'Content-Type: application/json; charset=utf-8' --header 'Authorization: Api-Token ${{ secrets.DYNATRACE_API_TOKEN }}' --data '[{"schemaId":"builtin:management-zones","schemaVersion":"1.0.12","scope":"environment","value":{"name":"sample2","description":"sample description","rules":[]}}]'
